### ISSUE TITLE
Java-Jasmine

### ISSUE THREAD

**Issue by o1lab** [bvkatwijk/Java-Jasmine#2]
Hey @bvkatwijk : reaching out here.

To let you know that there will be a little delay in looking at swagger PR in xmysql.  I really appreciate your contribution.

**Comment by bvkatwijk** [comment]
Thanks @o1lab , I hope that some of the people calling for swagger support will gradually expand the coverage of the generated documentation.

**Comment by o1lab** [comment]
Thank you,
